- hosts: bastion
  vars:
    internet_type: "{{ lookup('env','GI_INTERNET_ACCESS') }}"
    domain: "{{ lookup('env','GI_DOMAIN') }}"
    is_one_node: "{{ lookup('env','GI_ONENODE') }}"
    ics_size_hint: "{{ lookup('env','GI_ICS_SIZE') }}"
    ics_admin_password: "{{ lookup('env','GI_ICSADMIN_PWD') }}"
    bas_ip:  "{{ lookup('env','GI_BASTION_IP') }}"
    install_gi:  "{{ lookup('env','GI_INSTALL_GI') }}"
    gi_version:  "{{ lookup('env','GI_VERSION') }}"
    gi_namespace:  "{{ lookup('env','GI_NAMESPACE_GI') }}"
  
  tasks:
  - name: Check other configuration parameters
    fail: msg="Variable {{ item.name }} is not set"
    when: item.value == ""
    loop:
      - { name: "GI_INTERNET_ACCESS", value: "{{ internet_type }}" }
      - { name: "GI_DOMAIN", value: "{{ domain }}" }
      - { name: "GI_ONENODE", value: "{{ is_one_node }}" }
      - { name: "GI_BASTION_IP", value: "{{ bas_ip }}" }
      - { name: "GI_ICSADMIN_PWD", value: "{{ ics_admin_password }}" }
      - { name: "GI_INSTALL_GI", value: "{{ install_gi }}" }
      - { name: "GI_VERSION", value: "{{ gi_version }}" }
      - { name: "GI_NAMESPACE_GI", value: "{{ gi_namespace }}" }

  - name: Set parameters for air-gapped installation
    set_fact:
      repo_user:  "{{ lookup('env','GI_REPO_USER') }}"
      repo_user_password:  "{{ lookup('env','GI_REPO_USER_PWD') }}"
    when: internet_type == 'A'

  - name: Check configuration parameters for air-gapped installation
    fail: msg="Variable {{ item.name }} is not set"
    when: internet_type == 'A' and item.value == ""
    loop:
      - { name: "GI_REPO_USER", value: "{{ repo_user }}" }
      - { name: "GI_REPO_USER_PWD", value: "{{ repo_user_password }}" }

  - name: Set masters array
    set_fact:
      node_ip: "{{ lookup('env', 'GI_NODE_IP').split(',') }}"
      node_mac: "{{ lookup('env', 'GI_NODE_MAC_ADDRESS').split(',') }}"
      node_name: "{{ lookup('env', 'GI_NODE_NAME').split(',') }}"

  - name: Set GI installation variables
    set_fact:
      gi_case_inventory_setup: "install"
      gi_case_archive: "ibm-guardium-insights-2.0.0.tgz"
      offline_inventory: "gi_offline"
      ics_size: "{{ 'small' if ics_size_hint == 'S' else 'medium' if ics_size_hint == 'M' else 'large' }}"

  - debug:
      var: ics_case

  - name: Check presence of cloudctl tool
    stat:
      path: "/usr/local/bin/{{ item.file }}"
    register: cloudctl_tool
    with_items:
      - { file: "cloudctl" }
    ignore_errors: true

  - name: Stop if cloudct tool is not available
    fail:
      msg: "Install ICS before GI"
    with_items: "{{ cloudctl_tool.results }}"
    when: item.stat.exists == False 

  - name: Start portable registry
    shell:
      cmd: "{{ item }}"
    loop:
      - podman start bastion-registry
    when: internet_type == 'A'

  - name: Create GI operator namespace
    shell:
      cmd: "oc create namespace {{ gi_namespace }}"
    ignore_errors: yes

  - name: Switch GI inventory to portable registry
    shell:
      cmd: "cloudctl case launch --case ../gi-temp/{{ offline_inventory }}/{{ gi_case_archive }} --inventory {{ gi_case_inventory_setup }} --action configure-cluster-airgap --tolerance 1 --args \"--registry registry.{{ domain }}:5000 --user {{ repo_user }} --pass {{ repo_user_password }} --inputDir {{ offline_inventory }}\""
    when: internet_type == 'A'

  - name: Wait for cluster reconfiguration
    pause:
      minutes: 3
    when: internet_type == 'A' and is_one_node == 'N'

  - name: Wait for cluster operators after mirrored operator images setup (can take 20-40 minutes)
    shell:
      cmd: "oc get co --config=../ocp/auth/kubeconfig --no-headers|awk '{ print $3$4$5 }'|grep -v TrueFalseFalse|wc -l"
    register: co_status
    until: "co_status.stdout == \"0\""
    retries: 150
    delay: 20
    when: internet_type == 'A' and is_one_node == 'N'

  - meta: end_play

  - name: Create ICS catalog file
    template:
      src: ics_catalog.j2
      dest: "../gi-temp/ics_catalog.yaml"
    when: internet_type != 'A'

  - name: Publish ICS catalog
    shell:
      cmd: "oc apply -f ../gi-temp/ics_catalog.yaml"
    when: internet_type != 'A'

  - name: Publish ICS catalog in air-gap
    shell:
      cmd: "cloudctl case launch --case ../gi-temp/{{ offline_inventory }}/{{ gi_case_archive }} --inventory {{ ics_case_inventory_setup }} --action install-catalog --namespace {{ ics_operator_namespace }}  --args \"--registry registry.{{ domain }}:5000\""
    when: internet_type == 'A'

  - name: Wait for ICS catalog
    shell:
      cmd: "oc get pods -n openshift-marketplace|grep opencloud-operators|grep 1/1|grep Running|wc -l"
    register: ics_catalog_status
    until: "ics_catalog_status.stdout == \"1\""
    retries: 30
    delay: 10

  - name: Wait for ICS catalog source
    shell:
      cmd: "oc get catalogsource -n openshift-marketplace|grep opencloud-operators|wc -l"
    register: ics_catalog_source_status
    until: "ics_catalog_source_status.stdout == \"1\""
    retries: 30
    delay: 10

  - name: Subscribe ICS operator
    shell:
      cmd: "oc apply -f ../scripts/ics_subscription.yaml"

  - name: Wait for ICS csv
    shell:
      cmd: "oc -n common-service get csv|grep ibm-common-service-operator|grep Succeeded|wc -l"
    register: ics_csv_status
    until: "ics_csv_status.stdout == \"1\""
    retries: 30
    delay: 10

  - name: Wait for ICS crd's
    shell:
      cmd: "oc get crd | grep operandrequest|wc -l"
    register: ics_crd_status
    until: "ics_crd_status.stdout == \"1\""
    retries: 30
    delay: 10

  - name: Set ICS deployment size
    shell:
      cmd: "oc patch commonservice common-service -n ibm-common-services --type=\"json\" -p='[{\"op\": \"replace\", \"path\": \"/spec/size\", \"value\": \"{{ ics_size }}\"}]'"

  - name: Wait for deployment size change
    shell:
      cmd: "oc get commonservice common-service -n ibm-common-services -o json|jq -r .status.phase"
    register: ics_commonservice_status
    until: "ics_commonservice_status.stdout == \"Succeeded\""
    retries: 30
    delay: 10

  - name: Generate operands file
    template:
      src: "ics_operands.j2"
      dest: "../gi-temp/ics_operands.yaml"

  - name: Deploy ICS
    shell:
      cmd: "oc apply -f ../gi-temp/ics_operands.yaml"

  - name: Wait for operands deployment initiation
    pause:
      minutes: 3

  - name: Wait for successful ICS deployment (takes 20-60 minutes)
    shell:
      cmd: "oc get pods --no-headers -n ibm-common-services|grep -v Completed|grep -v Running|wc -l"
    register: ics_pods_status
    until: "ics_pods_status.stdout == \"0\""
    retries: 80
    delay: 20

  - name: Check pod's containers status
    shell:
      cmd: "oc get pods -n ibm-common-services|grep Running|awk '{print $2}'|awk -F'/' '$1!=$2'|wc -l"
    register: ics_containers_status
    until: "ics_containers_status.stdout == \"0\""
    retries: 80
    delay: 20

  - name: Login to ICS
    shell:
      cmd: "cloudctl login -a https://cp-console.apps.{{ domain }} -u admin -p `oc -n ibm-common-services get secret platform-auth-idp-credentials -o jsonpath='{.data.admin_password}' | base64 -d` -n kube-system"

  - name: Set ICS admin password
    shell:
      cmd: "cloudctl pm update-secret ibm-common-services platform-auth-idp-credentials -f -d admin_password='{{ ics_admin_password }}'"

  - name: Wait for authentication changes
    pause:
      minutes: 3

  - name: Wait for successful password change
    shell:
      cmd: "oc get pods --no-headers -n ibm-common-services|grep -v Completed|grep -v Running|wc -l"
    register: ics_pods_status
    until: "ics_pods_status.stdout == \"0\""
    retries: 80
    delay: 20

  - debug:
      msg:
        - "IBM Common Services {{ ics_version }} installation finished"
        - Update the hosts file on your web browser workstation
        - "{{ node_ip[0] if is_one_node == 'Y' else bas_ip }} console-openshift-console.apps.{{ domain }} oauth-openshift.apps.{{ domain }} cp-console.apps.{{ domain }}"
        - "Login to ICS console as admin user - https://cp-console.apps.{{ domain }}"
