- name: Login to local image registry
  ansible.builtin.shell:
    cmd: "podman login -u {{ repo_user }} -p {{ repo_user_password }} registry.{{domain}}:5000"

- name: Import images to local registry (it can takes more than one hour)
  ansible.builtin.shell:
    chdir: "../download"
    cmd: "oc-mirror --from ../download/{{ocp_release}} docker://registry.{{domain}}:5000"
