temp_dir: "../gi-temp"
skip_phase: 0
registry_version: "2.8.1"
matchbox_version: "v0.10.0"
rook_operator_version: "v1.9.13"
rook_ceph_version: "v16.2.10"
cp4s_channel: "1.10"
ics_versions: [ "3.14.2", "3.18.0", "3.19.4", "3.20.1"]
ics_cases: [ "1.10.2", "1.14.0", "1.15.4", "1.16.1" ]
ics_operator_namespace: "common-service"
ics_case_name: "ibm-cp-common-services"
ics_case_inventory_setup: "ibmCommonServiceOperatorSetup"
gi_versions: [ "3.2.0"]
gi_31_32_index: 3 #array index where 3.2.x starts
gi_cases: [ '2.2.10' ]
gi_case_inventory_setup: "install"
offline_inventory: "gi_offline"
cp4s_versions: [ "1.10.3" ]
cp4s_cases: [ "ibm-cp-security-1.0.28.tgz" ]
cp4s_case_inventory_setup: "ibmSecurityOperatorSetup"
px_channel: "stable"
px_version: 2.11.2
